### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by trekab**
I have cloned the 'thenextweb.com' page focusing on the responsiveness of the page. I look forward to getting a response about the way I have implemented the project requirements.

Microverse Requirements(https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)
Odin Project Requirements(https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-responsive-design)

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 
Hi @trekab :wave: 

I understand this is supposed to be a collaborative project. Could you please enlighten us on the reason you did it solo?

That said, I must commend your efforts; you have done a good job so far. However, let's address the following issues:

### Navigation bar
#### Large version
- [ ] It contains a **main navigation** row.
- [ ] It contains a **sub-navigation** row.
- [ ]  It contains a search icon at the rightmost side of sub-navigation row.

#### Small version changes
- [ ] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to search icon). _You seem to be missing the search component_

**Please submit another code review request after fixing these issues**


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by trekab** [comment]
I worked alone on this collaborative project because of my coding partner not being able to continue with me. The student success team resolved that I can work alone on the remaining projects until I finish the HTML/CSS section.

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 
Hi @trekab :wave: 

Nice work, it looks much better now. However, the logo seems to have disappeared for **large and medium** breakpoints. Can you please fix that? Also, don't you think the navigation links should actually be links?  `<a>` :wink: 

**Please submit another code review request after fixing these issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by trekab** [comment]
I have fixed the logo issues on the medium and large screens.

**Comment by shshamim63** [comment]
## Changes Required!
Hi @trekab, :wave:
impressive work. Well organized indentation and perfectly use of HTML tags :clap: . Well, for sure I can say you are on the right track :wink: . To declare this project as complete, need to work a little bit more. Well i am sure you will crack them :boom: . Please follow the instructions below to complete this project :point_down: .
##### Mandatory Changes:
1.  Fix the logo image for the medium size window.
logobar
#### Hint :point_right: Inspect the element and try to play with position of the logo. Or you can fix the issue by positioning navbar as you did with the logo.
2. For mobile window the footer is not possessing the full width.
footer
3. It is better to avoid repetition on your code. For an example in CSS file you have used  
`.main-header {
  display: none;
}` and
`.logo-article {
  display: none;
}`
though both are same. So can't you use a unique name? 
:fire: Why you have to do that? Please check this [link](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/).
##### Optional Changes:
1. The consistency of font size of the latest news section with respect to its image is not eye catching. 
fontsize
#### <em>Please submit another code review request after fixing these issues</em>

Happy coding :star: :v:
Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat Hossain)

**Comment by trekab** [comment]
I have finally managed to implement the feedback I received plus some more polishing up on the page.

**Pull request merged**
